### ISSUE TITLE
Default settings are only used in form and not applied to course unless recompletion course settings page saved.

### ISSUE THREAD

**Issue by abias** [danmarsden/moodle-local_recompletion#160]
Steps to reproduce: 
* Go to /admin/settings.php?section=local_recompletion
* Set local_recompletion | recompletiontype to "On Demand"
* Set local_recompletion | quizattempts to "Delete existing attempts"
* Create a course
* Enrol a student into the course
* Go to the course recompletion settings within a course and have a look at the settings
* You will see that "Recompletion type" is set to "On Demand" as expected
* You will see that "Quiz attempts" is set to "Delete existing attempts" as expected
* Go to the "Modify course completion dates" page

Expected result:
* The student is listed in the user table
* The 'Reset all completion' link is shown in the user's row which allows you to reset the course completion for this user.

Actual result:
* The student is listed in the user table
* The 'Reset all completion' link is not shown in the user's row. You cannot reset the course completion for this user.

Analysis:
* If the course recompletion settings has never been saved yet for an existing or newly created course, the course recompletion settings shows the plugin's default settings. However, in this case, there isn't any entry for this course in the local_recompletion_config table yet until the settings page is saved. 
* Because of that fact, resetting a course completion manually is not possible before the settings page is saved even if the global default "Recompletion type" is set to "On demand". The UI does not reflect this fact in any way.

Background information:
We are using local_recompletion in a way purely to manually reset course completions of particular users. We do not use the Period or Schedule "Recompletion type", just the "On Demand" recompletion type.
Resetting the course completions should be possible for every course based on the global settings without saving the recompletion settings in each course first.

**Comment by danmarsden** [comment]
Thanks Alex, 

I think I'd go down the route of using an event listener on the course creation and then if the receompletion type default is not set to RECOMPLETION_TYPE_DISABLED then save all the default settings for the course.

Then - in the course settings form - don't use the "site default" anymore for the recompletion type setting, so that if the course doesn't actually have it's settings saved, then it shows as being disabled.

I'm not a big fan of an upgrade step to change all existing courses that are currently disabled and enable them though.
