### ISSUE TITLE
Invalid default setting for recompletiontype

### ISSUE THREAD

**Issue by micaherne** [danmarsden/moodle-local_recompletion#166]
The default for recompletiontype is "range", which isn't in the valid set of values so causes failures of these core unit tests:

* ` \core\adminlib_test::test_admin_output_new_settings_by_page`
* ` \core\adminlib_test::test_admin_apply_default_settings`

(I haven't provided a pull request for this as I can't work out which of the options should be the default. If you can let me know I'll get a patch sorted out.)

**Comment by micaherne** [comment]
This seems to be fixed in the latest MOODLE_403_STABLE (I was using the latest version from the Moodle plugin db) so I'll close it :)

**Comment by danmarsden** [comment]
ah - thanks - that did sound familiar - just hadn't got a chance to come back and look - it was fixed in #157 

I've been spending most of the time I have available for "community stuff" on plugins db reviews recently to try and clear the backlog, but that's meant some of the stuff in my own plugins has needed to sit for a bit longer than I would normally like! - hopefully we'll clear that backlog soon and I'll get some time to come back to some of my own plugins...
