### ISSUE TITLE
MSSQL fails to cast values to integer - causing Scheduled Task to fail.

### ISSUE THREAD

**Issue by peverist** [danmarsden/moodle-local_recompletion#40]
Hi - hoping you can assist with this issue.
 
Recompletion scheduled task keeps failing with the error message 'The conversion of the nvarchar value '8639913600' overflowed an int column' - see attached log.

Initially ran ok but started failing once courses started using the option.
 
Running on Windows stack
Moodle 3.10.4 (Build: 20210510)
PHP 7.2.26
MSSQL 11.00.7493
local_recompletion | 2.02020122300

[local_recompletion_task_check_recompletion-129064.log](https://github.com/danmarsden/moodle-local_recompletion/files/6612626/local_recompletion_task_check_recompletion-129064.log)
![Server_Environment_2021-06-08_10-20-18](https://user-images.githubusercontent.com/75293765/121103549-87b3be80-c843-11eb-8a1b-1b1523c5aecb.jpg)

 Thanks - Phil

**Comment by danmarsden** [comment]
Hi There - 8639913600 is a weird value to have set in the recompletion_config table - I'd suggest you work out what course has that set and check the settings to see if they make sense.

Otherwise - as this is a MS SQl issue (which I do not support officially) - I'm unlikely to spend any further time as a volunteer on this.

Feel free to submit a pull request if you find something that helps!

**Comment by peverist** [comment]
Thanks - I found a course that was intended as a one off course with the option to manually recomplete and had been set with the maximum value of 99999 in the recompletion period field (with Days). This was updated to a lower value and the scheduled task ran successfully.
