### ISSUE TITLE
Add ability to set fixed recompletion date (eg all expire on 1st Jan every year)

### ISSUE THREAD

**Issue by keevan** [danmarsden/moodle-local_recompletion#86]
The idea is to have a fixed time period where course completions are simply reset for all users (who have completed the course), at a some fixed point(s) in time.

This has been requested by one of our clients, and we think it's a good idea to leverage the existing and standard cron format, as opposed to having a single date or dates in a text field to control the schedule.

An example would be to configure the reset to happen once a year, or bi-annually.

An example of once a year on Jan 1st is : `0 0 1 1 *`
See: https://crontab.guru/every-year

Whilst this might not be applicable for everyone, it's a good default, should the user/admin decide to apply leverage it.

Since this is a new feature request, it makes sense to keep the default behaviour (of a period of time after user completion), and have this be another option they could use to  configure the recompletions.

**Comment by danmarsden** [comment]
I don't have an issue with admin users needing to understand a ui that uses a cron format,  but it's not really a nice UI that I'd expect teachers to be able to understand, surely there are better ux designs we can choose from that allow a teacher to set this up without needing to understand "cron" format?

**Comment by keevan** [comment]
That's a fair point. I'm actually ripping what's in core, and potentially a better UX version could exist for both.

![image](https://github.com/danmarsden/moodle-local_recompletion/assets/9924643/6c23bd4a-6527-4f14-9d7c-ece1beef7616)

e.g. admin/tool/task/scheduledtasks.php?action=edit&task=auth_cas\task\sync_task
![image](https://github.com/danmarsden/moodle-local_recompletion/assets/9924643/7427932b-a804-470d-8bdf-daca1ba7e2df)

**Comment by danmarsden** [comment]
thanks for adding the screenshots - just posting what we discussed internally here as well... I think using cron based structure is fine for scheduled tasks because it's only the site-admin that has access to control those settings and it's probably fine to expect that a site-admin would be able to understand cron based UI settings, but I'm not convinced that teachers should have to understand this - it would be better IMO to use similar controls found in calendaring software which may not give the same "power" as cron timing might, but should be able to provide the functionality that a teacher requires in the recompletion plugin.

**Comment by danmarsden** [comment]
fyi - you are likely to get some code conflicts in this due to the other feature I've been working on this week (in PR #88) - I've tried to copy some similar setting names to your patch to make that a bit easier but that's likely to land in the core release before your patch sorry!

**Comment by danmarsden** [comment]
this has now been implemented with the new recompletion type - thanks @keevan !
