### ISSUE TITLE
Limit recompletion per enrolment method

### ISSUE THREAD

**Issue by dmitriim** [danmarsden/moodle-local_recompletion#96]
In my case I'd like to limit recompletion only for users enrolled using a specific enrolment method.

**Comment by danmarsden** [comment]
interesting idea - I suspect once we pull this thread there might be a number of other use-cases for restricting which users are handled through the recompletion process, just try to think about what might happen in future when writing the code for this so that it's easy to extend without having to completely rewrite how it's implemented.

**Comment by dmitriim** [comment]
Yeah. Could be implemented as sort of subplugin system. Same way it's done for activity types. 
Like each of the implementation should have two methods. One for adding SQL bist that will limit users in check_recompletion task and another that would receive userid and will return true or false depending on internal logic.

**Comment by danmarsden** [comment]
yeah - don't need to get too carried away in your first version - happy for it to just be a basic extension, but good to wrap important bits in functions where possible.
